import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Blockchain DApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Blockchain Examples
        </h1>

        <p className={styles.description}>
          Get started by using React, solidity, Smart Contract, Truffle.
        </p>

        <div className={styles.grid}>
          <a href="" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Please read a read me for setup and run</p>
          </a>

          <a href="" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js, Web app, deployment of smart contract in test network</p>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly create web app, write smart contract, deploy on test network, connect with MetaMask.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          Its Awesome
        >
          Creating Web app using React/nextjs .
        </a>
      </footer>
    </div>
  )
}
